language: python
dist: xenial
install:
  - pip install -r requirements-test.txt -r requirements.txt
jobs:
  include:
    - stage: test
      name: Code format check
      script:
        - black --check .
    - stage: test
      name: Lint
      script:
        - echo linting
    - stage: test
      name: Run Tests
      python: 3.7
      script:
        - nose2 -v
      after_script:
        - codecov
    - stage: deploy
      script: "/bin/true"
      deploy:
        provider: pypi
        user: andreroggeri
        skip_upload_docs: true
        skip_existing: true
        password:
          secure: k3+7VFIRIeCNXtMukoUu98TdbQkcYkEB8fGorRPq+gAuVQcq/NLXUWKD6id06r0mu2g5HD2s/xKfGkqHwvfvCsDVp3GqFrx+mPY2it8uDcbqQpXkl1Z4hFRwXX1zp54EwsAhu0turLeM+a6eVvpU13wpgZL/1QMBWvk2HI1xZzzSbs3YKg3ylARkb/1edtSfmMf9BrSHdTNvTIlzNHQYsB8VOtcpLvqvGnd4ehueEGBxI7ZdQp/y7f959esywZQeeZhneA8NKmsn4qFJQvN6kCIenJMs18wON8Sy8UoBPOjWoEJMQSMw4UdOAxN/620pyEgJqgLFCtTiooPnzn3nRmKduYPs4zMoYsDB/uTKwSJiJVRWCRTkeIrnVY2ygT5p0yKrkTtiw0y0wJzfIqKKk+qj3+xTzlAdTWKGTyTW81BApqdsMDnJkRfKTwqzJFFuvDFfjxDWanDI4zQlsflyxzo742h036g/iukdhQLg0duUiXsPJhTHKJWSZtecS+92Zi5OYmI9ksVUnqGEDiqYOH8i45AW6ZynPHBDnnRFw+dG8jEvhJJmRxnyUn8dWiI4urTJ6SHVJnvKPukLpUYhIQwHbZHtFOCUT+/dc7dV1ahKWOc0Pq0I+wnW/ULQUgqyB1AicHkv1+0OIuI62tyVSTccDApWpvE+pRkW9RBMTho=
        on:
          tags: true

